### ISSUE TITLE
Check what happens when the colors aren't specified for an object

### ISSUE THREAD

**Issue by mjuric** [dirac-institute/sorcha#1001]
Verify what happens if one runs Sorcha with a catalog of objects, not all of which have entries in the physical characteristics file (the one specified with `-p`).

The version presently on conda-forge doesn't fail in this case, but it's unclear how it computes the magnitudes it outputs.

**Comment by astronomerritt** [comment]
Ran the test set with one of the objects (2011_OB60) removed from the physical parameters file.

Sorcha ran without complaint, but 2011_OB60 did not appear at all in the results.

This is because of how the files are read in. I will try to be brief and probably fail.

- ObjIDs aren't checked until chunking. 
- The orbits file chunk is read first based on the chunk size. A list of the ObjIDs for the chunk are taken from this orbits chunk.
- If the ephemeris file is externally supplied, this is read next. The code scans through the ephemeris file and skips every row with an ObjID that is not in the list. This method does not care or error out if an ObjID in the list does not exist in the file.
- The physical parameters file is read next in the same way. 
- The code then checks to see if the ObjIDs in the physical parameters chunk are a _subset_ of those in the orbits chunk. (A comment in the code claims it's checking to see if the ObjIDs are a subset of those in the ephemeris chunk. This isn't true, it's checking against the "primary" dataframe, which is always the orbits dataframe.)
- Then, when all the dataframes are joined, we lose any entries in the orbits/ephemeris dataframes that don't have corresponding entries in the physical parameters dataframe.

We should discuss in the next meeting what should be done about this.
