### ISSUE TITLE
PPConfig example file for Rubin

### ISSUE THREAD

**Issue by Gerenjie** [dirac-institute/sorcha#389]
It would be very helpful to have a PPConfig.ini file, ideally the demo file, that is as Rubin-like as possible. The current file has some major differences from Rubin (observing_filters doesn't include u or y), and also includes enough settings that telescope non-experts (like me) might find it difficult to determine what is already set to Rubin baseline and what is not. 

Personally, I just did a bunch of work with a version of the PPConfig file I'd modified from the demo, and only realized late in the process that I needed to change the observing_filters setting.

**Comment by mschwamb** [comment]
Given that we don't have colors for u or y this may be the most Rubin-like already and with the current times we're prioritizing getting out the relevant filters. 

There's not complete documentation either because this in development, so this goes hand-in-hand with finishing the software development. If folks are running this, they should be talking to the Queen's folks about gotchas in the meantime.

**Comment by mschwamb** [comment]
I'll add this to the meeting agenda for July and August meetings

**Comment by drewoldag** [comment]
Include an increase to the default chunk size

**Comment by drewoldag** [comment]
This can evolve into a set of canonical config files, one for each appropriate survey.
