### ISSUE TITLE
Create temporary file MetaK_new.txt 

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/sorcha#526]
Something needs to create the meta kernel file that's called MetaK_new.txt used in the notebook. 

Since the location of the kernels might change or be copied over from a old directory, so maybe this is something that sorcha should do at runtime or maybe this should be produced by the bootstrap script

See Section 5 - https://naif.jpl.nasa.gov/pub/naif/toolkit_docs/FORTRAN/req/kernel.html#Recommendations%20on%20Kernel%20File%20Naming

**Comment by mschwamb** [comment]
Addressed in #516

**Comment by matthewholman** [comment]
Below is the content of the current meta kernel file.  Sorry for copying this here, but it might make the description easier.

The PATH_VALUES and PATH_SYMBOLS fields, along with the correspond symbols in the KERNELS_TO_LOAD expression, can be changed to correspond to wherever the files are stored.  I put them all in one directory, just to make it easy for myself.

We could set this up so that only PATH_VALUES needs to be changed.

\begindata
PATH_VALUES  = ( '/Users/mholman/Dropbox/support/kernels')

PATH_SYMBOLS = ( 'A' )

KERNELS_TO_LOAD=(
   '$A/naif0012.tls',
   '$A/earth_720101_070426.bpc',
   '$A/earth_200101_990628_predict.bpc',
   '$A/pck00010.tpc',
   '$A/de440s.bsp',
   '$A/earth_latest_high_prec.bpc')

\begintext

**Comment by matthewholman** [comment]
@drewoldag, it looks like you've already done this!

**Comment by drewoldag** [comment]
This was taken care of in #516, specifically this commit: https://github.com/dirac-institute/sorcha/pull/516/commits/fc6ffa2991861f13149e09b085efe610015d17e0#diff-be461de36d08fec9795f4d80df908d1694c04100213382c8b5d26e4e2d5729b3
