### ISSUE TITLE
Better initalization of t_picket

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/sorcha#591]
There's a line in the ephemeris generation jupyter notebook and in the sorcha implementation (see [here](https://github.com/dirac-institute/sorcha/blob/4fe07d831636ca6ccf91da3ffb9571d6d5ed7af8/src/sorcha/ephemeris/simulation_driver.py#L24) )that looks like it's an initialization step before the main for loop:
 
`t_picket = 2460000.5`

@matthewholman can your recommend a better way to initialize this variable based on the pointing database timings? Especially in the case someone tries to run an older rubin_sim cadence simulation that has an earlier start date than 2023.

**Comment by matthewholman** [comment]
The value used to initialize t_picket doesn't matter.  It just need to be set to something in order to not throw an error on the first pass.  The first time through (when first == 1) the values are updated and t_picket is reset to the current exposure time.  I know using the 'first' variable method is a little ugly, but it does avoid code duplication.

**Comment by mschwamb** [comment]
The answer is yes we're going to hardcode it to a different value see #666
