### ISSUE TITLE
Merge runLSSTPostProcessing and runLSSTSimulation 

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/sorcha#596]
Adding a formal ticket for merging runLSSTPostProcessing and runLSSTSimulation  and do the logic of whether ingesting a CSV file for ephemeris or using A+R in the combined function

**Comment by mschwamb** [comment]
#559 ated

**Comment by drewoldag** [comment]
This of items for this issue:

- [ ] Make use of the `-f` flag and warn the user if they are about to overwrite the ephemeris file
- [ ] Add new CLI argument for ephemeris output file name
- [ ] Add logic in main sorcha `while` loop to either call A&R for the chunk or read the ephemeris file chunk
- [ ] Return pandas dataframe from A&R. Append output of A&R to output file (due to chunking, don't want to overwrite the output for each chunk.)
- [ ] Provide a CLI argument to define where the A&D data files were downloaded.

**Comment by mschwamb** [comment]
Note because of possible chunking the  output the ephemeris csv file needs to be  appending to the file so that if the process is in the second or third iteration of the loop that it keeps adding to the bottom
