### ISSUE TITLE
Slowdown after update to rebound 4.0.3

### ISSUE THREAD

**Issue by KatKiker** [dirac-institute/sorcha#775]
Some uses of sorcha/assist seem to be slower since the rebound update to 4.0.3 (we noticed this while doing propagations with assist as well) 

For example, the command: `sorcha -c ./demo/sorcha_config_demo.ini  -p ./demo/sspp_testset_colours.txt -ob sorcha_input_sieg_10.csv -pd ./demo/baseline_v2.0_1yr.db -o v_402 -t v402` takes a few minutes to run when the rebound version is set to `"rebound==4.0.2"` but hangs for a long time on the latest version. The regular demo seemed to work okay, so it may be related to these specific orbits. (input file attached)
[impactor_orbits_sorcha.csv](https://github.com/dirac-institute/sorcha/files/13895607/impactor_orbits_sorcha.csv)

**Comment by mschwamb** [comment]
@gerenjie I think you're seeing the same thing for minimoons

**Comment by mschwamb** [comment]
Current guess is that this is not a unexpected slowdown as these are objects that really need to have high precision computations. We're further checking on this once new ephemeris patch for fastmoving objects is incorporated

**Comment by bernardinelli** [comment]
I have been able to both 
- reproduce this issue (with rebound 4.1.1.)
- change the rebound time step inside sorcha to the default previous to 4.0.3 and have the simulation (using @KatKiker 's inputs) run end-to-end.
So the culprit is rebound's new adaptive time step. Do we need this new adaptive time step, or is the previous setting enough for our purposes? @matthewholman - any thoughts?

Reading https://arxiv.org/abs/2401.02849, I think our use cases are safely encompassed by the old IAS15 time step

**Comment by KatKiker** [comment]
We were able to circumvent this by setting the min_dt as well (eg. sim.ri_ias15.min_dt = 1e-10), if that's preferable to using the old adaptive mode
