### ISSUE TITLE
Bad error message for incorrect aux file delimiter 

### ISSUE THREAD

**Issue by Gerenjie** [dirac-institute/sorcha#854]
When you run Sorcha with the config file specifying the wrong auxiliary file, the first thing to break is the observing filter matching, so you get the following error message which is unclear and unhelpful (I have gotten this dozens of times while running Sorcha myself):
ERROR: PPGetMainFilterAndColourOffsets: colour offset columns in physical parameters file do not match with observing filters specified in config file.

It would be nice to get a message saying "aux files don't appear to be separated by [comma/space]" instead.

**Comment by mschwamb** [comment]
It could be because the file isn't the correct format in terms of CSV versus space deliminator or could be incorrect headers. We could include check your input files or something like that to help guide the user a bit better

**Comment by astronomerritt** [comment]
Yeah, it's an oversight that specifying the wrong delimiter also triggers this warning message, which is meant to warn for something else entirely...

As Meg says it might be worth adding something like "This could be due to incorrect aux_format in config file". 

However, it's not hard to check for this explicitly, I think. Off the top of my head we could check the length of the first column name. If it's really long, the wrong delimiter has been used.

**Comment by mschwamb** [comment]
A good solution proposed by @jeremykubica 
`
This one is a bit tricky since a file without commas can still be a valid CSV (with one column). A reasonable approach here might be to add a "get_number_columns" function that reads in the beginning of the file and returns the number of columns. We could then check that number of columns > 1 for files where we know it has to be. Or, if we are confident that all files loaded with these functions will have at least two columns, we could just check that.`

**Comment by mschwamb** [comment]
Looks like it's still happening

If i run **sorcha_copy_demo_files** on the command line  and then edit  sorcha_config_demo.ini to have aux_format = csv and run

sorcha -c sorcha_config_demo.ini -p sspp_testset_colours.txt -ob sspp_testset_orbits.des -pd baseline_v2.0_1yr.db -o ./ -t testrun_e2e

I'm still getting the same error. Looks like this is not caught
