### ISSUE TITLE
mini difi does not work with tracklet made of 1 observation with 1 night and 100%

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/sorcha#902]
mini difi does not work with tracklet made of 1 observation with 1 night and 100% @Gerenjie  to put in more detail

**Comment by mjuric** [comment]
@Gerenjie , can you give me a bit more details here? I tried the `linkObject` function with just a single observation and it (correctly) failed to link it (returned 0xFFFFFFFFFFFFFFFF as the linked ID).

Alternatively, see if the version on `minidifi-fixes` branch resolves the issue.

**Comment by mschwamb** [comment]
If I recall correctiy it was something like this, though SSP_number_tracklets = 1 might not have been 1 

[LINKINGFILTER]


# SSP detection efficiency. Which fraction of the objects will

# the automated Rubin Solar System Processing (SSP) pipeline successfully link? Float.

SSP_detection_efficiency =1


# Length of tracklets. How many observations of an object during one night are

# required to produce a valid tracklet?

SSP_number_observations = 1


# Minimum separation (in arcsec) between two observations of an object required 

# for the linking software to distinguish them as separate and therefore as a valid tracklet.

SSP_separation_threshold = 0.5


# Maximum time separation (in days) between subsequent observations in a tracklet. 

# Default is 0.0625 days (90mins).

SSP_maximum_time = 0.0625


# Number of tracklets for detection. How many tracklets are required to classify

# an object as detected? 

SSP_number_tracklets = 1


# The number of tracklets defined above must occur in <= this number of days to 

# constitute a complete track/detection.

SSP_track_window = 15

**Comment by mjuric** [comment]
Ah, got it.

This is a bit of a degenerate case, as there's no linking to perform, which confuses the code which computes the number of discovery opportunities.

In a typical (`nlink>1`) case, each different combination of tracklets is counted as one opportunity. So, say we have tracklets at nights 1, 2, 5, 6, 9 with nlink=3, window=7. This would result in 4 unique discovery opportunities:

* at night 5 (with tracklets from nights 1, 2, 5)
* at night 6 (with nights 1, 2, 5, 6)
* at night 8 (with nights 2, 5, 6)
* at night 9 (with nights 5, 6, 9)

The lists in parentheses are basically all the unique combinations of nights with tracklets, in the trailing linking window. Note night 8: it's a night where no new observations are taken, yet we count it as a discovery opportunity as the tracklet from night 1 has now dropped out of the window, so the remaining combination (nights 2, 5, 6) is a new one for the linker to see. We do this because (in theory) the linker could be failing because tracklet from night 1 is confusing it, but now that it's out of the linking window it succeeds making the link with the remaining 3. This is a bit of a choice/guess as to how the linker will be behaving and isn't terribly precise (but generally doesn't matter for Rubin, given high heliolinx efficiency).

Back to the topic: for the `nlink=1` choice (leaving window=7), the above algorithm gets confused as it generates the following table:

* at night 1 (with night 1)
* at night 2 (with nights 1, 2)
* at night 5 (with nights 1, 2, 5)
* at night 8 (with nights 2, 5, 6)
* at night 9 (with nights 5, 6, 9)

These are all combinations of nights with at least one tracklet, in a 7-day trailing window. Hypothetically, the linker could behave differently when presented with these different combinations, so we could treat them as separate discovery opportunities. But in this special case, we know /exactly/ how the linker will behave -- as soon as it detects a tracklet, it will report it. So all these combinations would result in an /overcount/ of discovery opportunities.

I think the solution is to just special-case the `nlink=1` case, and immediately return the number of opportunities == number of nights with tracklets.

PS: While we're at it, `nlink=1` option realistically only makes sense if you can also control the minimum number of observations in a tracklet. E.g. "how many tracklets can Rubin report if we're only reporting 4-observation tracklets"? We should add that enhancement (later).

**Comment by mschwamb** [comment]
`PS: While we're at it, nlink=1 option realistically only makes sense if you can also control the minimum number of observations in a tracklet. E.g. "how many tracklets can Rubin report if we're only reporting 4-observation tracklets"? We should add that enhancement (later).`

Agreed. Can you make a ticket with the label enhancement so we can keep track?

**Comment by mjuric** [comment]
I just pushed the nlink=1 special case and added a unit test to test it. The fix was really simple, so why not do it. Should be resolved now (assuming I got it right).

**Comment by mjuric** [comment]
Resolved in #972
