### ISSUE TITLE
get answers to minidifi questions 

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/sorcha#942]
[miniDifi Issues.pdf](https://github.com/dirac-institute/sorcha/files/15267365/miniDifi.Issues.pdf)

**Comment by mjuric** [comment]
I think I have these sorted out on the [minidifi-fixes](https://github.com/dirac-institute/sorcha/tree/minidifi-fixes) branch, but I'd need someone to test it prior to merging.

There were three bugs, affecting two things -- a) two bugs around the calculation of the number of discovery opportunities (also affecting the calculation of whether the object has been discovered, but rarely in practice as Rubin linker has p=.95 and usually many discovery opportunities), and b) a bug where Sorcha could crash when computing the ID of the "asterisk-ed" observation (which was never triggered because of the other two bugs).

@astjoephysics , could you try running your notebook & see it they agree better now? If there are any differences, let's get together on Zoom & try to sort it out.
